### ISSUE TITLE
Hotspot error

### ISSUE THREAD

**Issue by WhiCCX0** [Pixel-Props/raven#1]
Android 11, Dotos, Gauguin, can't turn on hotspot after flashing the module. I don't know if it's my own problem, I'll close the issue if no one else has this problem.
![Screenshot_20211105-190334_dotOS_Launcher](https://user-images.githubusercontent.com/47388635/140501073-3a869a95-fda4-4334-a95c-16f83372ecd2.png)
![Screenshot_20211105-190517_dotOS_Launcher](https://user-images.githubusercontent.com/47388635/140501163-248177dc-0a89-4644-ac67-af77a1c6ae22.png)

**Comment by 0x11DFE** [comment]
Please use a Android 12 compatible ROM. And make sure your ROM security patch does match the module security patch.
