### ISSUE TITLE
Causing gms keep warning

### ISSUE THREAD

**Issue by WhiCCX0** [Pixel-Props/raven#6]
Module cause Google services to keep on WARNING, causing its cpu usage to be consistently high and consuming battery.
![Screenshot_20220612-211737_Logcat Reader Professional](https://user-images.githubusercontent.com/47388635/173235407-94155d8b-1f69-4583-8874-c6c1e2ec10a7.png)
![Screenshot_20220612-211754_Logcat Reader Professional](https://user-images.githubusercontent.com/47388635/173235412-dac8c980-c422-4993-8a7f-410d9f5e7c81.png)
![Screenshot_20220612-211759_Logcat Reader Professional](https://user-images.githubusercontent.com/47388635/173235415-af6e7423-f0eb-4430-8fe3-9977e154874f.png)
![Screenshot_20220612-211854_Scene4](https://user-images.githubusercontent.com/47388635/173235418-4611a361-1d08-4c0b-bf36-853b34a8d95d.png)

**Comment by thefiredragon** [comment]
Same issues

**Comment by WhiCCX0** [comment]
pm disable com.google.android.gms/.chimera.GmsIntentOperationService 


issues fixed
